blank_issues_enabled: false
contact_links:
  - name: Report a bug/Request a feature on Maicol07 Tracker
    url: https://tracker.maicol07.it/projects/77873802-c9cd-45a8-b425-1a3ce472d6ad
    about: To better organize the developer's work, issues should be created in the developer bug tracker. Please open an issue there and not here on Github. This is the only way to make sure your request is remembered and solved! Any issue created here on Github will be marked as invalid, as you should use the official bug tracker!
